-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."locked_token_distributions" add column "updated_by" bigint
--  not null;
